### PR TITLE
moon is testing automation

### PR DESCRIPTION
**Pull request by moonbuddy**
## Changes
_List Changes Introduced by this PR_
1. Item 1
2. Item 2

## Purpose
_Describe the problem or feature._

## Approach
_How does this change address the problem?_

## Learning
_Describe the research stage_

_Links to blog posts, patterns, libraries or addons used to solve this problem_

_If this closes an issue, reference the issue here. If it doesn't, remove this line_

### CODE REVIEW

**Comment by Big3D** [comment]
Task linked: [CU-3p6gww2 Moon Test](https://app.clickup.com/t/3p6gww2)

**Review by moonbuddy — COMMENTED** [review]
I'm reviewing something here.

**Review by moonbuddy — COMMENTED** [review]
Can this be a second review

**Review by gabymoreno9 — APPROVED** [review]
Looks good!

**Review by Eddie-Moreno — APPROVED** [review]
Looks good MB!

**Comment by gabymoreno9** [comment]
closing so its easy to see the dev PRs, this can be reopened anytime! :)

**Pull request closed without merging**
