### PR TITLE
style(font): applied Butcherman font to all

### LINKED ISSUE #77: Fonts and Styling (FSX) (CU-3q31z35)
<h3><strong>Desired Feature</strong></h3><p>Font to be spooky themed. <br/>Font Name: Butcherman<br/></p><h3><strong>Actual&#x2F;Current Behavior</strong></h3><p>Plain fonts currently.<br/></p><h3><strong>Steps to Implement</strong></h3><p>SEE BELOW<br/></p><h3><strong>Additional context</strong></h3><p><em>Add any other context or drop attachments below about the feature request here.</em><br/></p>

### PR DESCRIPTION
**Pull request by itannady**
## Changes
1. Import Butcherman font to CSS 
2. Applied Butcherman font-family to all 

## Purpose
Change font family to fit spooky theme

Closes #77

### CODE REVIEW

**Comment by Big3D** [comment]
Task linked: [CU-3q31z35 Fonts and Styling (FSX)](https://app.clickup.com/t/3q31z35)

**Review by Tabspear — APPROVED** [review]
Looks Good !

**Review by IvanPiceno171 — APPROVED** [review]
looks good

**Review by ChrisL119 — APPROVED** [review]
Great Job

**Pull request merged**
