### PR TITLE
fix: obstacle placement

### LINKED ISSUE #97: Obstacle placement (BUG) (CU-3qmabr4)
<h3><strong>Expected Behavior</strong></h3><p>The obstacles should be lowered so they can affect the behavior of the cat.<br/></p><h3><strong>Actual&#x2F;Current Behavior</strong></h3><p>Fix obstacle placement</p><ul><li>After the screen size fix, the obstacles are too high.</li></ul><p><br/></p><h3><strong>Steps to Reproduce the Problem</strong></h3><p>SEE CHECKLIST BELOW<br/></p><h3><strong>Testing Steps</strong></h3><p><em>How do the users test this change?</em><br/>SEE CHECKLIST BELOW<br/></p><h3><strong>Environment</strong></h3><p><em>Please provide **OS Version** and **Platform&#x2F;Browser**.</em><br/></p><h3><strong>Learning (Optional)</strong></h3><p><em>Describe the research stage.</em><br/><em>Links to blog posts, patterns, libraries or addons that could be used to solve this problem.</em></p>

### PR DESCRIPTION
**Pull request by itannady**
## Changes
1. Updated obstacle positions to reflect fixed canvas size
2. Updated obstacle sizes 

## Purpose
Fixed obstacle placement based on new canvas size.

Closes #97

### CODE REVIEW

**Comment by Big3D** [comment]
Task linked: [CU-3qmabr4 Obstacle placement (BUG)](https://app.clickup.com/t/3qmabr4)

**Review by Kendallfuller97 — APPROVED** [review]
Looks Good

**Comment by itannady** [comment]
Need to create obstacle class. Will make updates and push the changes in a bit!

**Review by IvanPiceno171 — APPROVED** [review]
great job

**Review by Tabspear — APPROVED** [review]
Looks Awesome !!

**Pull request merged**
