### PR TITLE
Gm 4 scrolling screen

### LINKED ISSUE #4: Scrolling screen
Description:

Scrolling screen

Tasks:

- Add background image to play scene
- Screen moves when moving right 
- Imagine the screen in thirds, when you move to the right third the screen begins scrolling ( ||stay| stay| move|| )

### PR DESCRIPTION
**Pull request by gabymoreno9**
## Changes
_List Changes Introduced by this PR_
1. added background image class
2. refactored obstacles to not move with the screen
3. refactor to ensure when a player reverses they don't get points taken away

Closes #4

### CODE REVIEW

**Comment by gabymoreno9** [comment]
https://user-images.githubusercontent.com/25145605/195687597-2ee1df0f-a237-4652-8f4c-6242cac81877.mp4

**Review by Aksume — COMMENTED** [review]
I just tested it looks good

**Review by ChrisL119 — COMMENTED** [review]
Looks good. Nice work!

**Review by itannady — APPROVED** [review]
Amazinggg!! Looks great!

**Review by IvanPiceno171 — APPROVED** [review]
great job on adding the background

**Pull request merged**
