### PR TITLE
feat(obstacle): add images to classes

### LINKED ISSUE #54: Add Images to obstacles (FSX) (CU-3pxazm4)
<h3><strong>Desired Feature</strong></h3><p>Add images to the obstacles.<br/></p><h3><strong>Actual&#x2F;Current Behavior</strong></h3><p>Adding images to the obstacles.<br/></p><h3><strong>Steps to Implement</strong></h3><p><em>Add a list of the steps required to implement this feature.</em><br/></p><h3><strong>Additional context</strong></h3><p><em>Add any other context or drop attachments below about the feature request here.</em></p>

### PR DESCRIPTION
**Pull request by itannady**
## Changes
1. Add images to obstacle classes

- saw sprite image (for both horizontal and vertical saw classes)
- water drop image
- skeleton hand image

## Purpose
Replaced placeholder obstacle squares with images

Closes #54

### CODE REVIEW

**Comment by Big3D** [comment]
Task linked: [CU-3pxazm4 Add Images to obstacles (FSX)](https://app.clickup.com/t/3pxazm4)

**Review by Tabspear — COMMENTED** [review]
Looks awesome ! Great Job !

**Review by Tabspear — COMMENTED** [review]
Also I don't seem to find the pies

**Review by IvanPiceno171 — APPROVED** [review]
great job

**Pull request merged**
