### PR TITLE
Fix: Added Score to ScrollPosition, timerbonus

### LINKED ISSUE #155: Fix score issue
Currently the score is only equal to the player position. The score should be the player position and the pies collected.
Potential fix is to separate the 2 score values then add them together for the combined score.
Also change the pies score to 500 to better see when you collect a pie.

### PR DESCRIPTION
**Pull request by Tabspear**
## Changes
_List Changes Introduced by this PR_
1. Improved on the score feature and added the score of the eaten pies to  score of the scroll position.
2. Improved on  the timer bonus to multiply with the left time in the timer. 

## Purpose
_Describe the problem or feature._

## Approach
Resolves the score problem. 

_Links to blog posts, patterns, libraries or addons used to solve this problem_

_If this closes an issue, reference the issue here. If it doesn't, remove this line_
Closes #155

### CODE REVIEW

**Review by itannady — COMMENTED** [review]
The time bonus says 99 even when the time is at 0. Also, is the score only suppose to change every time Sonic eats a pie? 

Screenshot 2022-10-30 at 12 02 21 PM

**Comment by Tabspear** [comment]
> The time bonus says 99 even when the time is at 0. Also, is the score only suppose to change every time Sonic eats a pie?
> 
> Screenshot 2022-10-30 at 12 02 21 PM

You only get full Timer Bonus if you complete the game before the timer runs out. Otherwise, you get 99 as a take away score.

**Comment by Tabspear** [comment]
> > The time bonus says 99 even when the time is at 0. Also, is the score only suppose to change every time Sonic eats a pie?
> > Screenshot 2022-10-30 at 12 02 21 PM
> 
> You only get full Timer Bonus if you complete the game before the timer runs out. Otherwise, you get 99 as a take away score.
E1p2Ltk7r5

**Review by itannady — COMMENTED** [review]
Just pulled the changes! The timer bonus says 100 even though the the timer is at 0. It should return 0 instead of 100 since there's no time left. 

image

**Review by Big3D — CHANGES_REQUESTED** [review]
The score should be updating in the animate function, not just when the pies are picked up.
A solution would be to create a variable called 'pieScore' and increment that when you pick up a pie. So in the GetScore() function you are then adding the pieScore total to the scroll position for the total score.

**Review by Big3D — APPROVED** [review]

**Pull request merged**
